# Generated by Django 2.1.2 on 2018-10-24 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'BŁĄD'), (10, 'Zainicjowano'), (20, 'Treść stron załadowana'), (30, 'Obiekty załadowane do bazy')])),
                ('url', models.URLField()),
                ('html_data', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('stop_time', models.DateTimeField(blank=True, null=True)),
                ('public_id', models.CharField(blank=True, max_length=7)),
                ('status', models.IntegerField(choices=[(1, 'BŁĄD'), (2, 'Zatrzymano przetwarzanie'), (10, 'Inicjuję'), (20, 'Zainicjowano'), (30, 'Ładuję adresy stron'), (40, 'Adresy stron załadowane'), (50, 'Ładuję treść stron'), (60, 'Treść stron załadowana'), (70, 'Ładuję obiekty do bazy'), (80, 'Obiekty załadowane do bazy'), (90, 'Czyszczę dane'), (100, 'Zakończono')])),
                ('category_url', models.URLField()),
                ('objects_limit', models.IntegerField()),
                ('pagination_limit', models.IntegerField(blank=True, null=True)),
                ('jobs_count', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='jobs.Session'),
        ),
    ]
