# Generated by Django 2.1.2 on 2018-10-31 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='transformed_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
