# Generated by Django 2.1.2 on 2018-10-31 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_transformed_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectorError',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('code', models.IntegerField()),
                ('message', models.CharField(max_length=63)),
                ('connection_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='connection_errors',
            field=models.IntegerField(default=0),
        ),
    ]
