# Generated by Django 2.1.2 on 2018-10-27 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vubu_id', models.IntegerField()),
                ('short_name', models.CharField(max_length=15)),
                ('full_name', models.CharField(max_length=63)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='ClotheSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='ClotheSizeDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=31)),
                ('value', models.IntegerField(blank=True, null=True)),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='offers.ClotheSize')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('vubu_id', models.IntegerField()),
                ('title', models.CharField(max_length=63)),
                ('code', models.CharField(max_length=7)),
                ('code_detail', models.CharField(max_length=31)),
                ('series', models.CharField(max_length=7)),
                ('description', models.TextField(blank=True, null=True)),
                ('price_old', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('price_new', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('available_sizes', models.CharField(max_length=63)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='offers.Category')),
            ],
        ),
        migrations.AddField(
            model_name='photo',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='offers.Product'),
        ),
        migrations.AddField(
            model_name='clothesize',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='offers.Product'),
        ),
    ]
